lecture7/8 code refactoring
Shwepsik/Yalantis pull request #4
Opened 2019-10-15 01:21 UTC by Shwepsik

2019-10-15 18:36 UTC, yalantis-ios-school requested changes
Опять проблемы с пониманием работы layout. Настоятельно рекомендую изучить Гайд по Autolayout.

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/AppDelegate.swift
> +        firstTabBarVC.tabBarItem = UITabBarItem(
Логика по созданию UITabBarItem должна быть внутри UIVC. Зачастую только контроллер должен знать, как настроить этот item. Остальным снаружи это знать не надо.

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/Cell/SettingsTableViewCell.swift
> +        answerLabel.snp.makeConstraints { (make) in
Autolayout нельзя настраивать в layoutSubviews. Тем самым ты создаёшь дубликаты. Читай об autolayout по ссылкам из лекций.

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/Models/MainModel.swift
> +                self.save(answer!)
Тут нужно сделать обработку на answer == nil, потому что в противном случае ты получаешь потенциальный креш. Или же API должна чётко говорить, что будет либо error, либо answer (см. типы Either и Result, но для тестового это не обязательные типы).

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/Models/MainModel.swift
> +                let answer = AnswerModel(answer: phrase, timestamp: Date())
timestamp можно сделать значением по умолчанию.

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/Models/MainViewModel.swift
> +    // Не добавлял форматирование с presentableAnswer.timestamp (string) в Date т.к делаю Predicate по ответу и в данном случае мне не важно какой Date(), если так лучше не делать то добавлю
Тогда API должна отражать то, что ты удаляешь по ответу. Зачем создавать целую модель, если удалить нужно по строке?
Плюс, не ясно, что будет при наличии двух ответов с одинаковыми ответами :)

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/Models/MainViewModel.swift
> +        let formatter = DateFormatter()
Форматер можно и нужно закешировать, чтоб не создавать его каждый раз - это довольно трудоёмкая операция

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/Models/MainViewModel.swift
> +    func dateToString(date: Date) -> String {
Лучше назвать по аналогии с форматером - у него именование более лаконичное:
func string(from date: Date) -> String

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/Services/PersistenceService.swift
> +        /*add necessary support for migration*/
Комментарии тут излишни.

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/Services/PersistenceService.swift
> +    lazy var backgroundMOC = persistentContainer.newBackgroundContext()
private(set) не хватает, так как в противном случае изменить значение контекста можно будет извне.

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/Services/PersistenceService.swift
> +        mainMOC.automaticallyMergesChangesFromParent = true
Это задаётся один раз при создании контекста в init. Каждый раз нет нужды это делать.

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/Services/PersistenceService.swift
> +        if backgroundMOC.hasChanges {
Лучше всё же сохранять необходимый контекст, а то у тебя нет понимания того, какой именно контекст нужно сохранить. А ну как изменения на главном, то что тогда? Имхо, если есть ссылка на контекст, то проще его по месту сохранить.

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/Services/PersistenceService.swift
> +     Какой смысл в фетче через fetchedResultController если при условии 3х слойной архитектуры на выходе я получу PresentableModel, только для делеагата и таблицы?
В принципе, данная архитектура ставит небольшие палки в колёса - это правда. Но в любом случае если ты не напрямую работаешь с CoreData, то нужна обёртка. Суть NSFRC даже в трёхслойной архитектуре только тот, что он даёт тебе гранулированные изменения (добавление по индексу, удаление, обновление и т.п.). 
Это то, что ты можешь после накатить на таблицу и получить красивую анимацию. В противном случае единственные способ обновить таблицу будет перезагрузка, но для пользователя тогда не совсем ясно, что именно поменялось.

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/Services/PersistenceService.swift
> +     Какой смысл в фетче через fetchedResultController если при условии 3х слойной архитектуры на выходе я получу PresentableModel, только для делеагата и таблицы?
Да, NSFRC можно не использовать и просто слушать сохранения всех контекстов и фильтровать их по нужному типу / предикату. Это по сути то, что делает NSFRC.

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/Services/PersistenceService.swift
> +        fetchRequest.sortDescriptors = [NSSortDescriptor(key: "timestamp", ascending: false)]
Сырые строки в этом случае можно получить через `#keyPath(ManagedAnswer.timestamp)`. Эта штука доступна для всех objc свойство.

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/Services/PersistenceService.swift
> +        backgroundMOC.performAndWait {
Не нарушение:
В данном конкретном случае нет необходимости работать с фоновым контекстом - можно выборку производить прямо на главном потоке. Суть по факту одна и та же, хотя у тебя этот подход более потокобезопасный.

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/Services/PersistenceService.swift
> +            save()
Тут уместнее будет не общий save вызвать, а сохранить непосредственно сам контекст.

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/Services/PersistenceService.swift
> +        fetchRequest.predicate = NSPredicate(format: "answer == %@", answer.answer)
По строкам аналогично комменту выше

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/Views/SettingsViewController.swift
> +            if self.alertTextField.text!.isEmpty {
В таком случае лучше сделать if let text = self.alertTextField.text, !text.isEmpty { ...
Это безопаснее.

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/Views/SettingsViewController.swift
> +                self.tableView.reloadData()
Не баг:
Разница с подпиской на изменения состояния БД в том, что обновление состояния и реакция на него (перезагрузка таблицы) происходит в одном месте в коде, что уменьшает количество потенциальных багов.
Это к вопросу о том зачем нам NSFRC

2019-10-15 18:36 UTC, yalantis-ios-school commented on Yalantis_School/Views/SettingsViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: cellReuseIdentifier) as? SettingTableViewCell
Лучше сделать guard let cell = .... as? Type else { fatalError(...) }
или же можно метод, который будет типизировано возвращать ячейку и из типа ячейки будет создавать идентификатор через `String(describing: type(of: T.self))`

2019-10-16 12:40 UTC, Shwepsik commented on Yalantis_School/Models/MainModel.swift
> +                self.save(answer!)
У меня же есть проверка на nil, после которой я уверен, что ответ получен.
Или вы имели в виду, что апи шара может прислать что угодно?
Но тогда меня выкинет на этапе Decodable.
А если они изменят поля, то наверняка у них есть своя миграция, т.к. есть Апи от которых зависят тысячи приложений и изменения полей в лоб приведёт к крашу. 
Это если я правильно понял, то что вы имели в виду?

2019-10-16 12:44 UTC, Shwepsik commented on Yalantis_School/Views/SettingsViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: cellReuseIdentifier) as? SettingTableViewCell
Добавил функцию:

func createCell<T: UITableViewCell>(_ anyCell: T.Type) -> T {
        let cellIdentifier = String(describing: anyCell)
        let cell = tableView.dequeueReusableCell(withIdentifier: cellIdentifier) as? T
        return cell ?? T()
    }

Но у меня есть сомнения в ее расположении. Оставил в SettingsViewController т.к там эта функция вызывается и только во ViewController'aх есть UIKit

2019-10-16 12:49 UTC, Shwepsik commented on Yalantis_School/AppDelegate.swift
> +        firstTabBarVC.tabBarItem = UITabBarItem(
Создавая TabBarItem во viewDidLoad() каждого контроллера приводит к тому, что при загрузке приложения сетится только первый(и это логично), именно поэтому я их там и сетил. В гугле сотни решений на этот счет, но хотелось бы услышать ваш вариант

2019-10-16 13:54 UTC, yalantis-ios-school requested changes

2019-10-16 13:54 UTC, yalantis-ios-school commented on Yalantis_School/AppDelegate.swift
> +        firstTabBarVC.tabBarItem = UITabBarItem(
А что если его в init перенести? А то не до конца понятно, что именно означает "сетится только первый"

2019-10-16 13:54 UTC, yalantis-ios-school commented on Yalantis_School/Models/MainModel.swift
> +                self.save(answer!)
Просто если смотреть на API конкретно тут, то никакого понимания того, что при error == nil у нас будет answer != nil нет. Это системой типов никак не выражено. Вот и вся проблема. Даже если под капотом там есть какие-либо проверки, клиент (этот класс) никак о них не знает. (ты не в счёт). 
По поводу миграции и апи по тысячам приложений не совсем понял.

2019-10-16 13:54 UTC, yalantis-ios-school commented on Yalantis_School/Views/SettingsViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: cellReuseIdentifier) as? SettingTableViewCell
Можно сделать что-то а-ля:

```
extension UITableView {

  func dequeueReusableCell<T: UITableViewCell>(for indexPath: IndexPath) -> T {
    // тут force unwrap уместен. 
    return dequeueReusableCell(withIdentifier: String(describing: type(of: T.self)), for: indexPath) as! T
  }
}
```

Этот файл ты можешь поместить отдельно в проекте, а после вызывать так:

let cell: SomeConcreteType = tableView.dequeueReusableCell(at: indexPath)

2019-10-17 13:02 UTC, yalantis-ios-school approved these changes

2019-10-17 13:02 UTC, yalantis-ios-school commented on Yalantis_School/AppDelegate.swift
> +        tabBarController.persistenceService.saveMainMOC()
во-первых, этому здесь не место

во-вторых, для чего ты это делаешь?

2019-10-17 13:02 UTC, yalantis-ios-school commented on Yalantis_School/Base.lproj/Main.storyboard
>  <?xml version="1.0" encoding="UTF-8"?>
для чего это файл всё еще сутсвует? ты же уже не пользуешься им

2019-10-17 13:02 UTC, yalantis-ios-school commented on Yalantis_School/Models/MainViewModel.swift
> +        return result!
от форс анврапа нужно избавиться

2019-10-17 13:02 UTC, yalantis-ios-school commented on Yalantis_School/Views/SettingsViewController.swift
> +        self.view.addSubview(tableView)
сначала нужно добавить таблицу на вью и залейаутить, а уже потом назначать ей делегат и датасурс

это связано с тем, что она сразу пытается отрисоваться а делать это пока негде

2019-10-17 13:02 UTC, yalantis-ios-school commented on Yalantis_School/Views/SettingsViewController.swift
> +        cell.answerLabel.text = answerPack[indexPath.row].answer
дважды обращаешься в массив за ответом. это не эффективно. достань объект в переменную и работай с ней

2019-10-17 13:02 UTC, yalantis-ios-school commented on Yalantis_School/Services/PersistenceService.swift
> +                print("Saved")
все эти принты нужно убрать. захожу в приложение а у меня консоль уже грязная

2019-10-22 20:42 UTC, merged